---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
# - typecheck # Gives a lot of useless errors
# - require_not_found
formatter:
  rubocop:
    cops: all
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 0
